---
# tasks file for final
- name: Deploy NGINX Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: default
        name: nginx-app
        labels:
          app: nginx-app
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: nginx-app
        template:
          metadata:
            labels:
              app: nginx-app
          spec:
            containers:
              - name: nginx-app
                image: 543066576745.dkr.ecr.us-east-2.amazonaws.com/finaltask:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
            imagePullSecrets:
              - name: regcred 

- name: Create NGINX Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: default
        name: nginx-app
        labels:
          name: nginx-app
      spec:
        selector:
          app: nginx-app
        type: NodePort
        ports:
          - protocol: TCP
            port: 8080
            nodePort: 30010
            targetPort: 80
